### ISSUE TITLE
【出展物】トートバック展示用台

### ISSUE THREAD

**Issue by tussytussy** [maruty/A_pj#101]
トートバック展示用の棚？台？フック？等の用意

#100の関連タスク

**Comment by maruty** [comment]
@tussytussy 
こんなかんじでいかがざんしょ？
![img_2948 1](https://cloud.githubusercontent.com/assets/6624979/15037415/d177f8ca-12d5-11e6-9f96-d22892bc4175.JPG)

**Comment by tussytussy** [comment]
ブラボー！！
ええやん！！

**Comment by tussytussy** [comment]
クローズします～
