### ISSUE TITLE
【出展物】販売物のお品書き作成

### ISSUE THREAD

**Issue by tussytussy** [maruty/A_pj#102]
販売一覧表の作成。

**Comment by tussytussy** [comment]
オレの方の、展示参考例として

ポストカード　１００円
[亥1.pdf](https://github.com/maruty/A_pj/files/246127/1.pdf)
[未1.pdf](https://github.com/maruty/A_pj/files/246133/1.pdf)

シール　300円
[ぼーだー子.pdf](https://github.com/maruty/A_pj/files/246134/default.pdf)

**Comment by tussytussy** [comment]
あ、PDFにしちゃった。
問題あれば、連絡くださいな～

**Comment by maruty** [comment]
@re0w0na  @tussytussy 
この辺　脱電の絵とかくれれば　シルバーウィーク序盤でオレが作りますよ（実際のデザインを貼り付けるところとかはお願いしたいですけど・・・・）

**Comment by maruty** [comment]
@tussytussy @re0w0na 
11/11 打ち合わせで確認する

**Comment by maruty** [comment]
販促物は以下の通り
・名刺は１００枚切ってたら１００枚add
・名刺サイズのLineスタンプが出来たよ　脱電くん200枚

@re0w0na できるだけ早く 僕にチケット下さい。

**Comment by maruty** [comment]
つっしーご確認ください　間違えてスタンプ販促100枚になっちまいましたが
あしからず・・・・
![ss 2016-11-20 1 13 14](https://cloud.githubusercontent.com/assets/6624979/20456696/cea8f2ea-aebe-11e6-8b38-3a120de1d619.png)

**Comment by tussytussy** [comment]
さすがやん。
んでは、確認したのでこちらもクローズします~。
