### ISSUE TITLE
【Web】情報の更新

### ISSUE THREAD

**Issue by maruty** [maruty/A_pj#106]
もろもろ情報更新した方が良いかもね  
Lineスタンプとかの話とかあるので・・・・

**Comment by maruty** [comment]
とりあえず　オレと @tussytussy にしておいた

**Comment by tussytussy** [comment]
脱伝くんをもっとゴリ推ししたい気はする。
おれの作品リスト等は、ちょうど今週末にでもまた作ろうと思ってたから更新はするが、
LINEスタンプの情報は大大的に行きたいよね。

あと、前に作った脱伝くん動画を入れとくとか。

**Comment by maruty** [comment]
@tussytussy 
いったん脱電クンの動画を youtubeにあげてそれをWebに組み込めるように検討と実施シアmす。

**Comment by tussytussy** [comment]
よろっす。

**Comment by maruty** [comment]
・TOPに動画を乗っける
・レナのスタンプを乗っける

**Comment by maruty** [comment]
@tussytussy いったん更新しましたのでご確認お願いします。

**Comment by tussytussy** [comment]
確認しました~。いい感じやね。
今回のはこの辺までかと思うから、一旦クローズします~。
