### ISSUE TITLE
れなのやること【脱電くん】

### ISSUE THREAD

**Issue by re0w0na** [maruty/A_pj#15]
脱電くんはまだザックリ

＝＝＝＝スケジュール＝＝＝＝
3月いっぱい　ロゴ作成
　　　　　　　　　脱電くんでなにかつくれるか（ポストカード？缶バッチ？）検討費用と期間
4月以降も沢山イラスト描いてLINEスタンプ作れるようにやってみる

データ出来次第共有的にうｐしていきます。

H27/2/26　れな

**Comment by maruty** [comment]
@re0w0na このチケットなんですけど全体概要は　wiki
https://github.com/maruty/A_pj/wiki
に記載したのでクローズします
