### ISSUE TITLE
出展者紹介分掲載

### ISSUE THREAD

**Issue by tussytussy** [maruty/A_pj#16]
デザインフェスタホームページ内でvol.41のご出展内容の紹介の件。
プロモーション用として。

①.まずはコレ読んで
■受付期間　：　2015年4月14日(火)19時まで
■注意事項　：　・画像は4枚まで(容量: 合計800KBまで、保存形式: JPEG、カラ―設定: RGBのみ)
　　　　　　　　　　・画像1が出展者紹介一覧にアイコンとして掲載されます。
　　　　　　　　　　・画像1は正方形(450px × 450px以内)の画像のみ受け付けます。
　　　　　　　　　　・一度送信した内容の追加・変更は出来ません。
　　　　　　　　　　・紹介一覧のアイコンはランダム表示と掲載順に切り替えが出来ます。
　　　　　　　　　　・掲載までに1週間程度かかる場合がございます。

②。これを踏まえて、画像紹介4枚を次のようにしたい。
　　1枚目　：　脱電くんロゴ
　　2～4枚目　：　各員の出展物画像
　れなは2枚分の負担になるけど大丈夫かな？？
　文章も合わせて募集するんで、いい感じの募集中～

**Comment by maruty** [comment]
@tussytussy とりあえず出店画像とロゴのタスク切ったほうがいいかなと思うー

**Comment by maruty** [comment]
@tussytussy @re0w0na  このチケットで会話をして、他のチケットで各自のタスクを切ることにする

**Comment by maruty** [comment]
slack連携のテスト

**Comment by maruty** [comment]
@tussytussy これの場合俺の場合は今回紹介動画に寄せるとなると、もう画像としてオリジナルで何かやることはないと思うので　このタスクの俺のタスクはクローズしたいです。問題なければクローズしてください

**Comment by tussytussy** [comment]
了解
