### ISSUE TITLE
【全体】空間設計の確認

### ISSUE THREAD

**Issue by maruty** [maruty/A_pj#27]
空間設計の確認
どのように配置する？
必要な備品は？
広さは？

その辺りを踏まえて適当にアウトプットする。

**Comment by maruty** [comment]
とりあえず一旦作成したのでサブタスクとして確認タスクを起票します

**Comment by maruty** [comment]
![default](https://cloud.githubusercontent.com/assets/6624979/6654468/0da1e410-cb0a-11e4-8304-d2583d0c7bd7.png)

**Comment by tussytussy** [comment]
内容に関しては異議なしかな。この辺はマルの映像表現がどうなるかが、配置に影響が大きいと考えている
んで、色味・雰囲気は良いかと思いやす。
紹介パネル案も◎かと。
オレの要求としては#32に記載したけど、縦44cm×横40cmのポストカードスペースが欲しいです。
画像のパネルが並んでいる両端のいづれかあたりが狙いかな。

**Comment by maruty** [comment]
@tussytussy 
了解す　アドバイスありがとう。　ポストカードスペース了解です。
内容追記しておきます。

なおこれに関連して、これらの成果物を誰が作るか子チケットあげます

**Comment by maruty** [comment]
![ss 2015-04-04 13 32 04](https://cloud.githubusercontent.com/assets/6624979/6991434/21529660-dacf-11e4-8cce-9bc074a5548d.png)

**Comment by tussytussy** [comment]
確認しやした。センキュー

**Comment by maruty** [comment]
いったん　成果物チケットの　#37 で打ち合わせるのでクローズ
