### ISSUE TITLE
【ポストカード】現地の配置

### ISSUE THREAD

**Issue by tussytussy** [maruty/A_pj#32]
(木orプラ）ボードに12枚立てかけで置こうかと。
その為の置き板作成・用意。
あと、ポストカード収納用のビニル・POPの用意

**Comment by tussytussy** [comment]
机に置いた状態で、縦44cm×横40cmくらいのスペースを考えてます。

**Comment by maruty** [comment]
@tussytussy これはモノすべてつっしー側で用意してくれる認識であっている？

**Comment by tussytussy** [comment]
あってる。
ビバホームとかで買ってきます。

**Comment by maruty** [comment]
@tussytussy 了解です
どっかのタイミングで誰が何を買うかのまとめをしたほうがいいかもね
wikiでまとめるか購入チケット起票するかどーしよっか？

**Comment by tussytussy** [comment]
#44にて購入物のチケット作りました。
向こうでまとめるので、こちらはクローズします～。
