### ISSUE TITLE
【LINEスタンプ】広告

### ISSUE THREAD

**Issue by tussytussy** [maruty/A_pj#33]
つッしーにて既に申請中のスタンプが間に合えばその広告。
カラープリントしたものをポストカード台の横に広告用として配置。
作業が少量なので、このタスクにて作成+印刷作業管理で。

**Comment by maruty** [comment]
@tussytussy 了解っす　内容について全体　ざっくり図に　記載しておきます

**Comment by tussytussy** [comment]
いまだにラインから連絡きません～。もはや４か月経過。

**Comment by maruty** [comment]
@tussytussy いったつっしオープンしたチケットとして持っておいてください

**Comment by tussytussy** [comment]
スタンプ承認されました。
まだ反映されていないみたいだけど、クリエーター名は脱力伝電社にしてありやす。

**Comment by maruty** [comment]
@tussytussy 
いやっほーやったね！！！！それの広告もしようよ！

**Comment by tussytussy** [comment]
イエス！しかし売れないわ～。いま配当金341円ですぜ。
ッて事でここはクローズします。
