### ISSUE TITLE
【映像】内容検討

### ISSUE THREAD

**Issue by maruty** [maruty/A_pj#34]
■映像の内容について
基本的には紹介映像
スライド的な感じ（多少おしゃれに）で表現出来ればよいかと考えている

■投影について
PCモニター　それともプロジェクターでバックに？
バックにやる場合は距離が短いため短焦点プロジェクターが必要

意見ください

つっしーにチケット回すのでコメント書いたらレナにアサイン→レナは俺に返してください

**Comment by tussytussy** [comment]
■映像の内容ついて
マルの時間次第でよいのだが、紹介映像＋αにていけないかな？
理由は、マルにうま味が少なさそうに思えるんで。
例えば今までに使用した映像とか技術を駆使でもいいかな～とは思うけど、マルティ自身も紹介対象に
なるような何かがあれば。

■投影について
そもそもプロジェクターッて持ってる？？打ち合わせ時は買うような話も出てたけど、もし現状なければ
（当日までに無いのであれば）、ＰＣモニターでもよいかと。
他に費用がかかるしね。

**Comment by tussytussy** [comment]
前後したけど、♯23・♯16今確認しました。
上記に俺ああ書いてるけど、無理しない範囲で。

**Comment by maruty** [comment]
@tussytussy 
了解です！　ちょっといったん二人の紹介映像は作るだけ作って（スライドショーレベルかと思います）それ以外の実験的なものは時間があればやるみたいな感じでいこうかなと思います。

■写すものについて
プロジェクタ買わなかったのでこれはPCモニターで行きます！

**Comment by maruty** [comment]
@re0w0na レナさんチケット対応遅いのでつっしー問題なければクローズしちゃってください

**Comment by tussytussy** [comment]
了解。締めます～。
