### ISSUE TITLE
【映像】素材収集（つっし）

### ISSUE THREAD

**Issue by maruty** [maruty/A_pj#35]
紹介映像に使う画像を収集したいです
10枚程度いただけませんでしょうか？（最終的に同じサイズで構図が殆ど変わらなければリテイクOK）

**Comment by tussytussy** [comment]
ここに貼り付けかな？
やり方教えて。
あと、JPEGで良いのかな？？

**Comment by tussytussy** [comment]
今日の夜にマルに直接メールします～。

**Comment by maruty** [comment]
@tussytussy 
つっしーありがとうメール着弾確認しましたのでクローズしますー
