### ISSUE TITLE
【全体】空間設計の確認--具体的な成果物作成者

### ISSUE THREAD

**Issue by maruty** [maruty/A_pj#37]
#27 の内容を踏まえて誰が何を作る？
![ss 2015-04-04 13 32 04](https://cloud.githubusercontent.com/assets/6624979/6991437/53ac809e-dacf-11e4-8658-d3b91d142399.png)

**Comment by maruty** [comment]
@tussytussy 
つっし側で分担とかいったん考えてもらえませんか？

**Comment by tussytussy** [comment]
上記の内容で行く過程であれば、
分担決める前に提案として、
歴史紹介は各自作成でどうだろう？Ａ３サイズ等に企画を決めて、あとは各自作成。
あと、れなの写真展示スペースはポストカード横に配置する感じかな？

●つッしー
・机やパーテーション予約
・自分のポストカード用のパネル
・自分の歴史パネル
・自分用の販促用パネル（値段書いてるだけのＰＯＰになるかもしれんが）

●れな
・脱伝くんのバック用大判紙
　Ａ３・４あたりの紙を駆使してＡ１サイズあたりにする感じかなぁ
・自分の歴史パネル
・写真展示用のパネル？（もしくは直に壁に貼るなら、両面テープを当日持参ね）

●マル
・自分の歴史パネル
・机を覆う布とか用意
・各自で行う自分紹介用のフォーマット？的な台紙。各自作成とはいえ、統一感が必要かと思うので。
　たとえば、グレーバックにアーティスト名・作品・説明文の配置だけでも。

印刷が一つ問題なんだが、販売物以外はたとえばマルティ宅で印刷できたりするかな？

**Comment by maruty** [comment]
@tussytussy  
印刷に関してはうちのプリンタでもOKなので提供しますー
サイズ感とか具体的なイメージもネットの画像とかこれを買って各自で作るとか
仕切りがあれば対応しますー

歴史パネルの仕込みお願いします

布は俺が用意しようか？
色は白でいいかな？何か希望あります？

**Comment by tussytussy** [comment]
布頼めたらよろしく。白のシーチングッていったっけ？一番安いやつ。あーゆーのでいいかな～と。

**Comment by maruty** [comment]
@tussytussy 
了解ですいったWebで探しますー

**Comment by tussytussy** [comment]
![2](https://cloud.githubusercontent.com/assets/11159907/7330860/c73c6042-eb32-11e4-8030-b2ee3dcfe0b0.jpg)

上のイメージでパーテーションと机を頼んでおきました。
図はＣＡＤで書いてるんで、ほぼ実際の寸法関係として誤差はないかと。
机の横スペースがレナが座ってるイメージかなぁ。

**Comment by maruty** [comment]
@tussytussy 
図面ありがとう！これでいけそうだね！！
パネルの材料とかっていったん2日に買いに行く時に全て揃えるイメージだっけ？

**Comment by tussytussy** [comment]
そーね。一気に買い揃えるかんじ。
ただし、2日は夕方になる感じなんで、無理そーならそれ以外の日でも・・・

**Comment by tussytussy** [comment]
そーいや、マルの家の近所はハンズやな。そこで割と揃うか。

**Comment by maruty** [comment]
実際の当日の動きを考慮するチケットを別途起票したらクローズとする

**Comment by tussytussy** [comment]
#52にて当日の動きを起案しやした。クローズしちゃうよ？？
