### ISSUE TITLE
【購入物】

### ISSUE THREAD

**Issue by tussytussy** [maruty/A_pj#44]
各自で、用意する作品以外の物の『購入する人』『購入するタイミング』をまとめましょう。
ざっとこんなものが考えられます。
・会場装飾品
・作品展示用のパネルや台紙等
・値段表記のためのＰＯＰ的なもの
・売り物を梱包する紙・ビニル等

**Comment by tussytussy** [comment]
現状までのおおよそとして
つしー
・自分の作品展示用の木版
　　ビバホーム等で、ゴールデンウィークあたりに購入予定
・ポストガード用のビニル
　　ヨドバシあたりで、ゴールデンウィークあたりに購入

マルティー
・布（机装飾用）

**Comment by maruty** [comment]
@tussytussy 
布は了解同じくゴールデンウィークあたりで買おうと思うからGWに日にちを合わせて買いにいかない？

**Comment by tussytussy** [comment]
@maruty 
いいよ～。2日か3日あたりどう？

**Comment by maruty** [comment]
@tussytussy OKそしたら　2日にしよう！！　大丈夫かな？

**Comment by tussytussy** [comment]
@maruty 
すまん、仕事になってしまって、17時以降か別の日なら・・・

**Comment by tussytussy** [comment]
明日購入予定品を書き連ねます。

・布
テーブルを覆う用。色は白とか、白に近い色。寸法は110㎝×260㎝以上あれば机が隠れるはず。
あと、予備で少々買っておくかどーか要検討。
レナが座る予定の椅子にも被せる必要があるかな～と。雰囲気的に。

・作品展示用パネル（ポストカード用）
サイズは最低でも45㎝×40㎝。素材は6㎜厚程度のベニヤ板かな。付属品として、立てられるように後ろに足として木材を接着予定。※でかい写真たてみたいな感じ。
れなの作品も同じように飾るのであれば、２枚購入。もしくは横にサイズを倍として90×40㎝

・作品宣伝用パネル（ＬＩＮＥスタンプ告知用）
Ｂ５サイズ程度の発砲スチロール板を想定。倒れ防止の足も購入。のちに紙を接着して使用。

こんなとこかな。

**Comment by tussytussy** [comment]
モニター周りも布被せる？

**Comment by maruty** [comment]
@tussytussy 
 モニター周りも配線とかを考えると、やったほうが良いかもね！

**Comment by maruty** [comment]
#37 購入などのためのリンクとして記載

**Comment by maruty** [comment]
@tussytussy @re0w0na  布Webで探してみたんだけど
http://nuno1000.net/?pid=38817950

ここの布を余分に買っておけばいいかと 156 * 300 くらいで　1200円くらいだからここでもOKでは？
今日はなしさせてくださいー

**Comment by maruty** [comment]
布以外は購入済
布は今から買う

**Comment by maruty** [comment]
注文しましたー

**Comment by tussytussy** [comment]
さんきゅー

**Comment by tussytussy** [comment]
買い物は終了したと思うのでクローズします~
