### ISSUE TITLE
当日の動き

### ISSUE THREAD

**Issue by tussytussy** [maruty/A_pj#52]
現地の搬入可能時間が次の感じです。
５月１６日（土）　：　７：００～１０：４５
※開場は１１：００

これを踏まえて当日の動きだけど、こんな感じでどう？まずは提案として
９：３０　/　会場と別の場所で一度合流。(仮に新橋や有明等)
１０：００　/　駐車完了・会場入り

意見求む。

**Comment by tussytussy** [comment]
１ｈ前に会場入りできれば準備は十分可能かと。ただ、懸念事項が、
・れなのコスプレ時間
・布のカットは現地？？
・搬入渋滞(ピークは７：００～９：００らしい)

この辺に不安がある場合は３０分以上とか早めるのもありかなぁ。

事前合流を設けたのは、一応俺が全員分のパス持ってるから、万が一を考えて。

**Comment by maruty** [comment]
@tussytussy 
車を前日池袋もってきておいて
上野で8:00-8:30くらいにつっしーピックアップして行く感じにする？

**Comment by tussytussy** [comment]
了解！
駅の真正面だと車が混雑してそーだから、この辺でどう？？
上野駅　入谷口（岩倉高校前あたり）
http://www.navitime.co.jp/?lon=503212920&name=%E4%B8%8A%E9%87%8E%E9%A7%85%EF%BC%88%E5%85%A5%E8%B0%B7%E5%8F%A3%EF%BC%89&ctl=0190&lat=128558805

**Comment by re0w0na** [comment]
@tussytussy 
@maruty 

上記で了解、私は基本家で着替えとか済ませておくので、最後の化粧とウィっグのセットくらいにするつもりです。30分程度で済ませようと思います

**Comment by maruty** [comment]
当日完了したので閉じます
