### ISSUE TITLE
【ロゴ

### ISSUE THREAD

**Issue by maruty** [maruty/A_pj#53]
つっしーにロゴを送る

**Comment by maruty** [comment]
ai file
http://firestorage.jp/download/dd00a782d30eb103d15423892ac1919e4a4441c3

jpg file
http://firestorage.jp/download/0273352425c0a4b4c7fff51ff7e2c8c82f424b98

よろー

**Comment by tussytussy** [comment]
さんきゅー
クローズしやす。
