### ISSUE TITLE
当日持っていく物チェック用

### ISSUE THREAD

**Issue by tussytussy** [maruty/A_pj#54]
ザッと思いつくあたりを書いておきました。
当日は忘れ物のないように～！！

■全体
イス
文房具
箱ティッシュ(予備)

■つしー 
ポストカード（クリアパック共） 
缶バッヂ 
3人分の入場チケット(他の郵送された資料) 
名刺 
販売用のおつり(100円玉・50円玉) 
ポストカード台用の重り板 
缶バッチ置き用の皿 
値札 
はさみ 
ガムテープ(予備) 
カラーペン(予備) 
のこぎり(予備) 
シューグー(予備) 
PC？

■れな 
展示写真 
衣装 
名刺 
販売用のおつり(販売金額に合せた額) 
ポートフォリオ等 
コスプレ雰囲気に合せたイス用の布？的なもの

■まるてぃ 
PC(アダプタ共) 
モニター 
モニターとデスクを繋ぐヤツ 
駐車場券 
名刺 
机用の布(PC用もここから捻出？) 
パネル・立て札等のハンズの袋　☆破損注意
 　上記袋内容(紹介パネル・脱伝パネル・LINEパネル・ポストカード用板と置き足・両面テープ・接着剤・余りパネル・余り木) 
ポートフォリオ

こんな感じかな？
追加あれば追記してくださ～い

**Comment by tussytussy** [comment]
追加
■つしー
カメラ

■マルティ
ノートPC置く、台みたいなの
(必要かわからんが、机の下にPC隠しても床に直置きになっちゃうから。不要であれば大丈夫。)

**Comment by maruty** [comment]
完了したので閉じます
