### ISSUE TITLE
次回デザフェス

### ISSUE THREAD

**Issue by tussytussy** [maruty/A_pj#55]
今回はマジでお疲れ様でした！！

そんで、帰りの車でも話したけど、次回どーする？？

デザインフェスタvol.42
１１月２１日(土)、２２日(日)
ブースエリア申し込み期間
５月２２日～６月２日

結構考える期間がないッてヤツッす。
予定や費用も考えつつ、意見プリーズ

**Comment by tussytussy** [comment]
オレ個人的には、１１月ッてのは”年賀状推し”の一番いい時期だわ。

**Comment by maruty** [comment]
@tussytussy 

いいんじゃね？ｗ　出しちゃいますか？ｗ

**Comment by tussytussy** [comment]
あ、報告遅れましたが、頼んでおきました。抽選結果は6/16に出ます～。

**Comment by tussytussy** [comment]
次回分、当選しました！！　11月21日(土)の1日出展でございやす。

**Comment by tussytussy** [comment]
こちらはクローズしときます。
