### ISSUE TITLE
【名刺_共通】

### ISSUE THREAD

**Issue by tussytussy** [maruty/A_pj#56]

**Comment by tussytussy** [comment]
久々に使ったらいきなり間違えた。
全体名刺作成の件です。

**Comment by maruty** [comment]
これどんな感じで進めていく？ @tussytussy

**Comment by tussytussy** [comment]
では、こんな流れで。
①.ここで、名刺に必要と思われる内容を書き出す
　↓全員了解
②.デザインを投稿する（前回使ったオレのがあるので、参考例としてあとで載せておきます）
　↓全員了解
③.印刷を何処でやるか？何枚刷るか？等を考える。

**Comment by tussytussy** [comment]
名刺に必要な内容としては最低限、
・脱力伝電公社（チーム名として）
・ロゴ（小気味良い脱伝くんを選択）
・URL

要不要の検討項目として
・紹介文
・QRコード

ほかに何かあるかな？

**Comment by maruty** [comment]
@tussytussy 
QRコードって必要なもんなん？って事が気になったかな
あとは　役職を　脱伝ちっくにいれるとかね

エンジニア＝＞　えんじにあ　or   電気技師
デザイナー => でざいなぁ　or 絵描き技師

**Comment by tussytussy** [comment]
技師いい！！

QRコードはそうなんよ。なので、必須ではない項目として。

**Comment by maruty** [comment]
https://slack-files.com/T03PHNH5D-F0BC01YKG-059b1f9fae

**Comment by maruty** [comment]
@maruty がイラレでデザイン起こす

**Comment by maruty** [comment]
![ss 2015-10-10 12 54 30](https://cloud.githubusercontent.com/assets/6624979/10409138/9867d482-6f4d-11e5-8220-a01b04b840e7.png)

**Comment by maruty** [comment]
いったん作った　@tussytussy  確認してー
あわせて　裏の　電の　とこの　なつの正式表記
連絡先情報をください

**Comment by tussytussy** [comment]
いいですね～。
いくつか提案&注文が。

・オレのアドレスは、uketorisenyou2@yahoo.co.jp
・なつの表記はそのまま、　なつ　で。
・なつのアドレスはおれと一緒にしてください。
・なつの表記順列は、一番下で。
・TELは載せないようにしたいかな~

以上、確認よろしくお願いしやす。

**Comment by maruty** [comment]
@tussytussy 
了解致しました！そしたらそんな感じで
@re0w0na 
詳細情報下さい（メアドとか表示する内容ですね）

**Comment by maruty** [comment]
こちら下記スケジュールでいきます
11/7名刺デザイン完成
業者依頼

**Comment by maruty** [comment]
@tussytussy 
俺チョンボ。・・・・・まだやってねぇ・・・・ちょっと間に合う所探します

**Comment by maruty** [comment]
http://www.meishiryohin.com/delivery/

ここが翌日やってくれるから土日タスクでやるお

**Comment by tussytussy** [comment]
今、気ィついてよかったな。
紙ベースものだしな。多分いくらでもまだ調整きくぜよ。

**Comment by maruty** [comment]
![ss 2015-11-14 16 51 20](https://cloud.githubusercontent.com/assets/6624979/11162643/40468f60-8aef-11e5-9460-c91e22a02d32.png)

**Comment by maruty** [comment]
注文しますたー

**Comment by tussytussy** [comment]
了解センキュー！！

料金は費用の方に載せておきます。

**Comment by maruty** [comment]
@tussytussy @re0w0na 
発注完了なのでクローズします
