### ISSUE TITLE
【ホームページ作成】

### ISSUE THREAD

**Issue by tussytussy** [maruty/A_pj#57]
脱伝のホームページ作成

**Comment by tussytussy** [comment]
HPが構成された後に、【名刺】 #56にURL記入の予定。
なにか必要事項あれば、都度募集項目のチケット作成してもらう感じで良いかな？

**Comment by maruty** [comment]
@tussytussy 
これとりあえず優先して進めようと思うんだけど
いつまでにあればいいんだっけ？

あとドメインだけど
http://datsuden.com
上記でいいですか？

**Comment by tussytussy** [comment]
@maruty 
ドメインそれでいこう！！

関連予定は【名刺】【デザフェス紹介文】のみだから、そこまで急ぎではないものの9月中とかに上げられればよいかなと。
【デザフェス紹介文】は、10月23日締め切りなので、ここに掲載する事が最重要次項。10月22日くらいが最大引き伸ばした日程だね。

**Comment by maruty** [comment]
@tussytussy 
了解ですー
そしたらgithubにソースコードあげながら作業しようかな。
とりあえずドメイン取得とかから始めてまいりますー

**Comment by maruty** [comment]
◎ご契約者情報
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
【 ムームーＩＤ 】maruty
【　お　名　前　】柳澤 雄高
【メールアドレス】yanagisawa.trade@gmail.com
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

◎契約内容
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
【 ドメイン 】datsuden.com
【 契約年数 】1年
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

◎支払い内容
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
【 支払方法 】クレジットカード決済
【 支払金額 】￥ 734

　　ドメイン取得費用　価格（￥ 680）× 契約期間（1年）＝ ￥ 680
　　消費税　　　　　　￥ 54
　　合　計　　　　　　￥ 734
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

**Comment by maruty** [comment]
http://datsuden.com/

ドメインとりました
仮置きしてみれるようにはいったんした

**Comment by tussytussy** [comment]
センキュー！！

**Comment by maruty** [comment]
http://datsuden.com/
wordpress導入
記事投稿管理URL
http://datsuden.com/blog/wp-login.php
id passは別途共有

**Comment by maruty** [comment]
テーマの差し替えを実施

**Comment by maruty** [comment]
いったん時間的な制約も考えて　WP使用しないFWで作成完了
http://datsuden.com/

**Comment by maruty** [comment]
一旦作成したからクーズ
close
