### ISSUE TITLE
【会場】プロフィール文章

### ISSUE THREAD

**Issue by tussytussy** [maruty/A_pj#58]
デザフェスのwebサイトに記載の紹介文の件。
前回と同じでいいかな？

**Comment by maruty** [comment]
@tussytussy 
一応議論しようか
前回の文書貼ってもらえますか？

**Comment by tussytussy** [comment]
これ前回の文章ね。

■アーティスト情報
 　3人で脱力しながら活動しています。
 　イラスト・写真・映像・コスプレ・VJ.....etc

■作品について
　『女子』をテーマにした作品をおのおので脱力しながら作ってます。ポストカード等展示してますので是非お立ち寄りください。

**Comment by maruty** [comment]
@tussytussy 
■作品について
　『女子』をテーマにした作品をおのおので脱力しながら作ってます。ポストカード等展示してますので是非お立ち寄りください

↑の部分が変わるのではないかしら？
女子だったり　かわいい　だったり　そんな作品を脱力　脱力・・・・作ってますみたいな？？

**Comment by maruty** [comment]
↑でFIX　申請するまでopenしておく

**Comment by tussytussy** [comment]
本日、申請したのでクローズします。
