### ISSUE TITLE
【会場】プロフィール画像

### ISSUE THREAD

**Issue by tussytussy** [maruty/A_pj#59]
#58 と同時にデザインフェスタHPに掲載する紹介画像の件

概要は前回と同じだけど、
■注意事項　：　・画像は4枚まで(容量: 合計800KBまで、保存形式: JPEG、カラ―設定: RGBのみ)
　　　　　　　　　　・画像1が出展者紹介一覧にアイコンとして掲載されます。
　　　　　　　　　　・画像1は正方形(450px × 450px以内)の画像のみ受け付けます。
　　　　　　　　　　・一度送信した内容の追加・変更は出来ません。
　　　　　　　　　　・紹介一覧のアイコンはランダム表示と掲載順に切り替えが出来ます。
　　　　　　　　　　・掲載までに1週間程度かかる場合がございます。

これを踏まえて、画像紹介4枚を次のようにしたい。
　　1枚目　：　脱電くんロゴ
　　2～4枚目　：　各員の出展物画像。もしくは、前回の会場写真。

基本はこんな感じでどうかな？

**Comment by maruty** [comment]
@tussytussy 
問題なかとです！　レナにも聞いてみましょう
@re0w0na 
問題なければつっしーにチケット返してください

**Comment by re0w0na** [comment]
@tussytussy 
@maruty 

１枚目おっけーです！
2～4枚目の件なんだけど、個人の出展物ないしは作品は賛成。会場の写真は他のサークルと大差ないから写真は反対です～。

あとつっし－にチケット返す方法忘れちゃったんだけどどうすれば良いんだっけか～！

**Comment by tussytussy** [comment]
俺もチケットの返し方わからん。
が、意見了解です。
んじゃ、今後掲載用の画像をここにアップするようにしましょう。

**Comment by maruty** [comment]
@tussytussy 
右カラムの Assignee　とこ押して下さいまし！！
そうするとチケットを回せます！

**Comment by maruty** [comment]
脱電くん画像を　@re0w0na が選定　2枚
つっしーが　ぼーだー子選定　1枚
つっしーの1枚

**Comment by re0w0na** [comment]
@tussytussy 
@maruty 

これでどうでしょ、つっしーに返します


![cat2](https://cloud.githubusercontent.com/assets/11195993/10396790/550f2faa-6edf-11e5-8433-7b823d7d61f7.jpg)
![cat3](https://cloud.githubusercontent.com/assets/11195993/10396793/55c6e82a-6edf-11e5-9a91-c65ee7068f0f.jpg)

**Comment by tussytussy** [comment]
@re0w0na
さんきゅーです。
これ、脱ぴっぴがトップ絵でいいよね？

**Comment by tussytussy** [comment]
本日プロフの掲載申請したので、一旦クローズします。
