### ISSUE TITLE
【出展物】ポストカード_つッしー

### ISSUE THREAD

**Issue by tussytussy** [maruty/A_pj#60]
出展予定の内容。

①前回作成分ポストカード12パターン
②新作1~2パターン(来年の干支のサルをベースにした、完全に年賀状狙いのやつ)

**Comment by maruty** [comment]
@tussytussy 年賀状ということをもう少し推した　広告POPあってもいいかもね

**Comment by tussytussy** [comment]
そーなんよ！作ったポストカードをA5かA4くらいに拡大したヤツを飾ろうかと。広告POP付きで。

**Comment by tussytussy** [comment]
ポストカード発注まで完了したので、閉じます～
