### ISSUE TITLE
【出展物】映像作品用脚本

### ISSUE THREAD

**Issue by tussytussy** [maruty/A_pj#62]
#61 作成用の脚本作成。

**Comment by tussytussy** [comment]
これに関しては、映像作成タスクにどれくらい必要か？から追っかけになるね。
仮に１か月必要であれば10月アタマくらいまでが理想かな？

**Comment by maruty** [comment]
@tussytussy 映像というよりは、レナの絵作成にどれほどかかるのかも確認しないとね
映像に関しては半月〜1ヶ月というくらいでいけるかと思います！

**Comment by maruty** [comment]
@tussytussy 
いったん何本作るか決めない？
3本くらいのイメージなんだけどつっしーはどう考えている？

**Comment by tussytussy** [comment]
オレも3～5くらいかと。
マルに相談なのだが、可能であれば脱伝くんの他に「ぼーだー子」も2本くらい突っ込めればと思っての本数。
LINEスタンプ作ってるから、動かせる用の原画がある程度あるので作画はそこまで手間取らないハズ。

**Comment by maruty** [comment]
@tussytussy 
いーよー
っこれちょっと確認なんだけど
脚本：ベースつっしー　で　みんなでブレスト
絵：れな　＆　つっしー
編集：丸茶

上記の役割分担で合っている？

**Comment by maruty** [comment]
@tussytussy 
上記役割分担ベースで　全体のスケジュール感　見えるようにしたいなぁ〜
ブレスト会を対面で　１回設定してそこまでに仕上げるみたいな感じでスケジュールが組めると思うので。

**Comment by tussytussy** [comment]
@maruty
役割はこれでいいんじゃないかな？
対面はたしかに必要ね。てかみんなで考えた方がいいアイディア出そうだし。
脚本も結局は現状ある(つくる予定の)絵ありきだと思うんで、脱伝くんのは絵を見て決める感じかな、と。

いつやる？平日の前回みたいな感じであれば、オレは大概大丈夫と思う。

**Comment by tussytussy** [comment]
今月末の26日とか一回集まらん？夜じゃなくでもいいので。

**Comment by maruty** [comment]
@tussytussy 
26日　夜ならレナマルOKです！

**Comment by tussytussy** [comment]
じゃあ、26日土曜にいったん話しましょ～

**Comment by maruty** [comment]
脚本案
https://soldesignteam.slack.com/files/yanagisawa_maruty/F0BC1T85N/slack_for_ios_upload.jpg

**Comment by maruty** [comment]
BGM案
http://amachamusic.chagasi.com/image_honobono.html

**Comment by maruty** [comment]
作るもの決定
・脱電くんの紹介
・日常1
・日常2（塩苦手編）

**Comment by maruty** [comment]
各詳細タスクに落とし込んだのでクローズ
