### ISSUE TITLE
【出展物】シール_つッしー

### ISSUE THREAD

**Issue by tussytussy** [maruty/A_pj#63]
なつ原作のスタンプ『ぼーだー子』のシールを作成。
実は、ひとまずサンプルとして作成してみていて、明日か明後日には納品予定。

クオリティ次第では、脱伝くんグッズにシールも良さげな気がするので、今度サンプル郵送します。

**Comment by tussytussy** [comment]
個人的には、脱伝ステッカーとかPCに貼りたいです。

**Comment by maruty** [comment]
んじゃこのタスクはいったん @tussytussy  にアサインしてて、シールの感想FBをもらってそのあとどうするか考えよう！

**Comment by tussytussy** [comment]
シール、昨日投函してあるから今日届いてると思う。
ちなみに印刷注文したのはこちら↓
http://www.graphic.jp/

他でもたくさんやってるけど、オレみたくフォトショユーザーがシール印刷できるのは、探した中ではココくらいしかデカいとこが無かった感じ。（カットラインを作業パスで作成する内容がイラレと違うみたい）

**Comment by maruty** [comment]
@tussytussy 
了解　届いているのは確認したので　土日でチェックします。

**Comment by maruty** [comment]
@tussytussy 
シール見ましたこれはなかなかよいかもね
これとは別に　脱力伝電公社のロゴ入りでもありだと思います。

@re0w0na 
レナも確認してね

**Comment by tussytussy** [comment]
@maruty 
いいよね。利益率はポストカードに劣ると思うけど、手数としては悪くないかと。

**Comment by maruty** [comment]
今回は作った分だけ持っていく方針
