### ISSUE TITLE
【出展物】缶バッヂ

### ISSUE THREAD

**Issue by tussytussy** [maruty/A_pj#66]
缶バッヂ作成の件。
前回は脱伝くんの３パターン作成したけど、今回はどうします？

**Comment by maruty** [comment]
@tussytussy 今回もおんなじくらいのパターンかな？前回分の余りがあるから今回は別パターンを作るとよかとおもいます！！
@re0w0na にどれ作りたいか聞こう！

**Comment by tussytussy** [comment]
大きさも選択できるしね。

**Comment by re0w0na** [comment]
@tussytussy 
@maruty 

前のが結構な数残ってるので次回は多くとも２種類くらいで良いのかなと思ってる。
でもまあサイズちょっと大きめでもよいかな～と！

**Comment by tussytussy** [comment]
では、ちょっとサイズと値段調べてみます～。

**Comment by tussytussy** [comment]
前は、ここに注文してました↓
https://www.secondpress.us/price/index.html

マグネットやキーホルダーも作れるっちゃ作れるみたい。

**Comment by maruty** [comment]
@re0w0na 
今回どの脱伝君を缶バッチにするのか検討お願いします。

**Comment by maruty** [comment]
11月頭までに使うものをFIXさせること

**Comment by tussytussy** [comment]
多忙そうなので、絵を確定してもらえば、オレで発注掛けておきます。

**Comment by maruty** [comment]
@re0w0na 
レナさん絵の確定をお願いします

**Comment by re0w0na** [comment]
@tussytussy 遅くなってすみません、まだ間に合うようならこれでお願いします。難しいようなら今回話でも大丈夫です。すみません。



![default](https://cloud.githubusercontent.com/assets/11195993/10909840/12ac29f2-827f-11e5-8035-5fe93f587aca.jpg)
![default](https://cloud.githubusercontent.com/assets/11195993/10909855/2c66fdb8-827f-11e5-8432-7896273b9794.jpg)

**Comment by tussytussy** [comment]
上の2パターンの作成依頼かけました。

前回同等の32㎜径　各20個です。
金額は47円/個

**Comment by tussytussy** [comment]
来週中には届く予定かと。

**Comment by tussytussy** [comment]
と、いう事でクローズします。
