### ISSUE TITLE
【出展物】アクリルキーホルダー_れな

### ISSUE THREAD

**Issue by tussytussy** [maruty/A_pj#69]
前回聞いていたので、作成します～。

**Comment by maruty** [comment]
これも同じように @re0w0na 　がいつまでに何をしなければいけないかをタスク立てしてください

**Comment by maruty** [comment]
タスクたてをしたらこのチケットを閉じる（つっしーにチケットを返して下さい）

**Comment by re0w0na** [comment]
#82 アクキー申し込みも立てました。
タイトルに#69入れるの忘れちゃったすみません

@tussytussy チケット返します

**Comment by tussytussy** [comment]
んでは、クローズします。
