### ISSUE TITLE
【出展物】LINEスタンプ_れな

### ISSUE THREAD

**Issue by tussytussy** [maruty/A_pj#70]
脱伝くんスタンプ。
仮に当日まで販売開始されなくとも、申請中なだけでも効果はあると思う。

**Comment by re0w0na** [comment]
@tussytussy 
OKです！すすめていきます！

**Comment by maruty** [comment]
@re0w0na 
これざっくりいつまでに何をするのかタスク立てを @tussytussy 　の時のノウハウをベースに組み立てて下さい

**Comment by maruty** [comment]
@re0w0na 
いったんそこまでの作業を９月下旬までにしておくね

**Comment by maruty** [comment]
こちら子タスク立案できているっぽいんでクローズします
