### ISSUE TITLE
【ホームページ作成】載せるコンテンツ

### ISSUE THREAD

**Issue by maruty** [maruty/A_pj#71]
載せるコンテンツの議論

About
Blog的なやつ
ポートフォリオ
そんくらい？

案出しplease!

**Comment by tussytussy** [comment]
そーね。ぱッと浮かぶのそんなもんかな？
あとは、LINEへの誘導とかかな。

**Comment by maruty** [comment]
http://datsuden.com/
いったん　素材も含めて　26日に議論する　ボールは　俺持ちにしておく

**Comment by tussytussy** [comment]
ほほほほほーー！！
こりゃスゴいぜ！！

**Comment by maruty** [comment]
9/26打ち合わせ
実績欄を新規作成
今後については過去実績をDB化　写真　文章　クリエーター名でフィルタリング的なもの

**Comment by maruty** [comment]
イベント告知関係画像は脱電君にしゃべらせる

**Comment by maruty** [comment]
なつをメンバーに追加
しま夏

**Comment by maruty** [comment]
Twitterのアカウントを作る

**Comment by maruty** [comment]
google アナリティクスを仕込む

**Comment by maruty** [comment]
脱電のプロフィール（アバウトの↓？）

**Comment by maruty** [comment]
#80 をタスクとする

**Comment by maruty** [comment]
全体進捗の中での作業順番を整理
今月末までにマイルストーンを修正する

**Comment by maruty** [comment]
いったんすべてのコンテンツをひな形としてあげているがタスクとして最後まで何を載せるか考えたいためオープンにしておきます

**Comment by maruty** [comment]
作業終わったっぽいんで閉じますー
