### ISSUE TITLE
【ホームページ作成】Webにのせる素材提供

### ISSUE THREAD

**Issue by maruty** [maruty/A_pj#72]
@tussytussy 
過去実績の画像　zipにかためてください
文章下さい
2014年XX月DD日　なにやらなにやら

@re0w0na 
過去実績に使って欲しい画像　zipにかためてください
文章下さい
2014年XX月DD日　なにやらなにやら

**Comment by tussytussy** [comment]
確認しやした。数日中に送信します。

**Comment by tussytussy** [comment]
對馬

展示歴
2007年5月　デザインフェスタvol.25出展
2015年5月　デザインフェスタvol.41出展

作品歴
SOLveryJAM vol.2~5　フライヤー
pizza GONZO ロゴ
pizzeria trattoria　DaPe GONZO ロゴ
etc

**Comment by tussytussy** [comment]
![default](https://cloud.githubusercontent.com/assets/11159907/10472596/06ae5cce-725d-11e5-8ccd-b8276fca3fe6.jpg)

**Comment by tussytussy** [comment]
![default](https://cloud.githubusercontent.com/assets/11159907/10472627/7a4fa82c-725d-11e5-8a02-4e3af7134a4d.jpg)

**Comment by maruty** [comment]
@tussytussy 
すげえ・・・・いっぱいあるね・・・・

@re0w0na 
はやめにくださいませー

マイルストーンをいったん今月末に変更する

**Comment by tussytussy** [comment]
あ、なつの分忘れてた。

なつ

作品歴
LINEスタンプ『ぼーだー子』
https://store.line.me/stickershop/product/1092313/ja

**Comment by tussytussy** [comment]
![default](https://cloud.githubusercontent.com/assets/11159907/10563685/4dfa281e-75ce-11e5-8e39-bb8a53c1a476.jpg)

**Comment by maruty** [comment]
ごめんなさいこちらみんなあげてくれたけど
各自でアップするようにさせてください。

こちらの素材を使う可能性があるからチケットはオープンにしておきます。

**Comment by tussytussy** [comment]
@maruty 
オレ側の作業は完了です。
クローズよろしく

**Comment by maruty** [comment]
@tussytussy 
了解ー
@re0w0na  が終わったら閉じます

**Comment by maruty** [comment]
@re0w0na  終わったので閉じますー
