### ISSUE TITLE
【出展物】LINEスタンプ_れな_申請作業

### ISSUE THREAD

**Issue by maruty** [maruty/A_pj#76]
#70 Lineスタンプの申請を行う

**Comment by tussytussy** [comment]
たしか、ココ見ながら申請したよ～。

http://yuriannu.com/archives/270

申請期間を短くするために、過去のデザフェス出展写真をＨＰに掲載しとけばより良いかな？

**Comment by re0w0na** [comment]
@tussytussy 
つっしーありがとう！確認しました。

**Comment by maruty** [comment]
@re0w0na 
レナさんこちらの作業が遅れていればマイルストーン修正お願いします

**Comment by re0w0na** [comment]
申請したのでチケット閉じます
