### ISSUE TITLE
【出展物】映像作品用脚本_脱電くんの紹介

### ISSUE THREAD

**Issue by maruty** [maruty/A_pj#78]
#62 の子タスク　脱電くんの紹介

・つっしーがスクリプト作成   -10/4
・まりんちゃんに翻訳依頼　-レナさん -10/11
・録音作業@maruty 　 -つっしー   仮10/10
・映像作成　maruty      -10/25

こんなイメージ

**Comment by tussytussy** [comment]
ごめん、スプリクト用の絵コンテを、写真とかでいいのでどっかに乗っけてもらえん？？
手元に何もなかった。

あと、デニーズでもらったお金500円じゃなく5ピソだった。

**Comment by tussytussy** [comment]
ごめん、スプリクト用の絵コンテを、写真とかでいいのでどっかに乗っけてもらえん？？
 手元に何もなかった。

あと、デニーズでもらったお金500円じゃなく5ピソだった。

**Comment by tussytussy** [comment]
すまん、slackに載せてるんだったな。失礼しやした。

**Comment by tussytussy** [comment]
[自己紹介編台本.pdf](https://github.com/maruty/A_pj/files/6570/default.pdf)
こんな感じでどうでしょう？
一度見てみてください。

特に生みの親！れなさん。

**Comment by tussytussy** [comment]
英語版翻訳がキツい点について、アイディアの一つとしてオレが津軽弁に翻訳して話すという手立てもあります。

**Comment by maruty** [comment]
@tussytussy 
こちら今回のマイルストーンに間に合わないので見送りにします　その為　未定にします

**Comment by maruty** [comment]
@tussytussy 
どちらかというとこっちの方がいいかもね。

**Comment by maruty** [comment]
いったんチケットもらいます

**Comment by maruty** [comment]
これ多分今ある絵だけでなんとか形に出来るかもなので実施するかを 11/12に確認する
