### ISSUE TITLE
Webに写真を載せる作業

### ISSUE THREAD

**Issue by re0w0na** [maruty/A_pj#80]
＃76　Webに前の写真を掲載して下さい。
（LINEスタンプ早期承認の為）

**Comment by re0w0na** [comment]
![2](https://cloud.githubusercontent.com/assets/11195993/10139727/4668ba6e-663f-11e5-9ae8-00f1046c76a5.jpg)

**Comment by tussytussy** [comment]
![cimg2582](https://cloud.githubusercontent.com/assets/11159907/10471959/f0b2a4b8-7255-11e5-9476-7634cd6702f8.JPG)

**Comment by tussytussy** [comment]
![cimg2589](https://cloud.githubusercontent.com/assets/11159907/10471995/4634c984-7256-11e5-97de-6f3aead631d0.JPG)

**Comment by tussytussy** [comment]
![cimg2592](https://cloud.githubusercontent.com/assets/11159907/10472014/7bb52d7e-7256-11e5-8062-75213b5335b8.JPG)

**Comment by tussytussy** [comment]
![cimg2584](https://cloud.githubusercontent.com/assets/11159907/10472045/d3679ebc-7256-11e5-8319-4400b8ff519b.JPG)

**Comment by tussytussy** [comment]
![cimg2591](https://cloud.githubusercontent.com/assets/11159907/10472080/2f3d971e-7257-11e5-8bf2-5065acc80cd8.JPG)

**Comment by tussytussy** [comment]
こんな感じかな。

**Comment by maruty** [comment]
@tussytussy 
あざます　ちょっと編集したりする作業も必要なので、いったん今月中タスクに変更させて下さい

**Comment by maruty** [comment]
いったんこれ作業用にオープン

**Comment by maruty** [comment]
こちら全員自分自身の作業が終わった段階でクローズとする

**Comment by tussytussy** [comment]
オレでひとまず作業終了なので、トピ主じゃないけどクローズしちゃうよ？？
