### ISSUE TITLE
アクキー絵柄かく　#69

### ISSUE THREAD

**Issue by re0w0na** [maruty/A_pj#81]

**Comment by maruty** [comment]
@re0w0na 
これ進捗どんな感じっすかー？間に合いそうになかったらマイルストーン修正よろですー

**Comment by re0w0na** [comment]
@maruty 　イラスト完成したので閉じます
![default](https://cloud.githubusercontent.com/assets/11195993/10708949/a9d35246-7a56-11e5-81e7-90e907a6f5de.jpg)
