### ISSUE TITLE
アクキー申し込み

### ISSUE THREAD

**Issue by re0w0na** [maruty/A_pj#82]
会社決めて申し込み

https://mydoogoods.com/products/14
http://www.sunrisep.co.jp/03_goods/SP17_acryl_keyholder.html
http://bambiassist.com/goods-acrylickeyholder.html

**Comment by re0w0na** [comment]
#69

**Comment by maruty** [comment]
@re0w0na 
レナさんこちら遅れるようであればマイルストーン修正して下さい

**Comment by re0w0na** [comment]
@maruty 
@tussytussy 
申し込みは済んだんだけど、会社から繁忙期の為納期が間に合いませんって言われてしまった。他の会社も当たったんだけど、どこも一緒だそうで、申し訳ない。とりあえずとじます。
