### ISSUE TITLE
【ホームページ作成】全体とつっしーまわりのコンテンツ更新依頼

### ISSUE THREAD

**Issue by maruty** [maruty/A_pj#84]
#80 関係のタスク

いったんWebを更新しましたのでコンテンツ類の中身を流し込んで下さい（雛形を作っているので編集で直してもらえるとよいかと）
つっしーには忙しい中、申し訳ないけど全体部分の更新もお願いできませんか？
http://datsuden.com/
使い方は・・・・・Wordpressとかでググッて下さい
ログイン
http://datsuden.com/blog/wp-admin/
ID PASSはslack　参照

**Comment by tussytussy** [comment]
ちょっと見てみます。時間ください。

**Comment by tussytussy** [comment]
@maruty 
更新しときました~。ひとまず分として。確認よろ～

でも、TOP押したときにエラーメッセージ出るのは俺ではわからんのでよろしく。

**Comment by maruty** [comment]
@tussytussy 
修正しましたークローズしますー
