### ISSUE TITLE
【ホームページ作成】レナまわりのコンテンツ更新依頼

### ISSUE THREAD

**Issue by maruty** [maruty/A_pj#85]
いったんWebを更新しましたのでコンテンツ類の中身を流し込んで下さい（雛形を作っているので編集で直してもらえるとよいかと）
http://datsuden.com/
使い方は・・・・・Wordpressとかでググッて下さい
ログイン
http://datsuden.com/blog/wp-admin/
ID PASSはslack　参照

**Comment by re0w0na** [comment]
@tussytussy ざっくり更新しました～また変えるかもだけどいったんまわします

**Comment by tussytussy** [comment]
確認しました。マルティすげーなコレ。いいねいいね～！！！
返信遅れて申し訳ない。バタバタが激しいので、自分の分は更新します。

**Comment by re0w0na** [comment]
@maruty 
これ編集が終わればとじちゃっていいの？
