### ISSUE TITLE
【出展物】アクリルキーホルダー_れな

### ISSUE THREAD

**Issue by tussytussy** [maruty/A_pj#93]
デザフェスvol.43用

脱伝くんのアクキー作成

**Comment by re0w0na** [comment]
商品受け取ったらクローズにします。

**Comment by re0w0na** [comment]
そういえば絵柄が気に入らんかったから修正しました。
![default](https://cloud.githubusercontent.com/assets/11195993/14580043/e433b884-03fb-11e6-8eb0-43786ad14f42.jpg)

**Comment by tussytussy** [comment]
ここもクローズしときます。
