### ISSUE TITLE
【名刺】

### ISSUE THREAD

**Issue by tussytussy** [maruty/A_pj#96]
前回、結構配ったハズなので在庫確認お願いしたいっす。

足りないようであれば、追加注文かな。

**Comment by re0w0na** [comment]
在庫0なので追加注文するとまる様が申しております。

**Comment by tussytussy** [comment]
了解どす～。

**Comment by maruty** [comment]
◆ご注文情報――――――――――――――――――――――――――――◆
｜プラン　　データ入稿≪名刺≫
｜データ　　添付ファイル　C:\fakepath\名刺.ai
｜データ預かり　希望しない
｜台紙・サイズ　マシュマロ（ホワイト）　４号（91mm × 55mm）
｜印刷カラー　カラー×モノクロ
｜オプション　無し
｜印刷枚数　1種類　計100枚
◆―――――――――――――――――――――――――――――――――◆
印　刷　代　：　2260円/100枚
　同一名刺割引：－0円
【受取まで】　注文確認メール → 印刷 → 店頭受取
◆―――――――――――――――――――――――――――――――――◆
｜お 支 払 金 額　｜2260円
◆―――――――――――――――――――――――――――――――――◆

■印刷データ内訳■
【１】脱力伝電公社　100枚


発注しました

**Comment by tussytussy** [comment]
あざした。ではクローズします。
