### ISSUE TITLE
【出展物】缶バッジ

### ISSUE THREAD

**Issue by tussytussy** [maruty/A_pj#98]
前回より増やそうか？種類。

LINEじゃ無理そーなヤツとか、やっとく？
ある程度絞ってもらえばオレの方で注文しとくんで。

https://www.secondpress.us/price/index.html

**Comment by re0w0na** [comment]
![default](https://cloud.githubusercontent.com/assets/11195993/14732237/9ffe697e-0893-11e6-877c-2a000e0c104e.jpg)
![default](https://cloud.githubusercontent.com/assets/11195993/14732243/b0da0528-0893-11e6-8aea-39ac883f916b.jpg)
![default](https://cloud.githubusercontent.com/assets/11195993/14732246/b72ebe28-0893-11e6-91f7-8ab5f4a3737e.jpg)
![default](https://cloud.githubusercontent.com/assets/11195993/14732247/bcdd50a0-0893-11e6-94e4-cd4c4d3ab8f2.jpg)
![default](https://cloud.githubusercontent.com/assets/11195993/14732248/c2377f9e-0893-11e6-8eb9-d64ebf25dd4d.jpg)
![default](https://cloud.githubusercontent.com/assets/11195993/14732249/c603cb50-0893-11e6-9bd4-2780c0c8ed19.jpg)
![default](https://cloud.githubusercontent.com/assets/11195993/14732254/cdda722a-0893-11e6-9154-b49d14a2bc14.jpg)
![default](https://cloud.githubusercontent.com/assets/11195993/14732260/dd1383b2-0893-11e6-83c6-2ff598d1071b.jpg)

**Comment by re0w0na** [comment]
上ふたつは自分が気に入ってるもので「あざます」はあたらしくしたいなーと。
がくぶるはどうかな、つっしーからみてどうっすか？

「てへぺろ」と「ぴくぴく」は缶バッチ向きかなーと思ってピックアップしてみた。

LINEでボツったやつは結構修正しちゃったものが多くてあとは修正に悩んでるこの子達くらいしかいないから缶バッチ向かないかなーと思うけど、どうだろうか？

私的には新しくするの2個前後でもいいかなーと思ってる。
「あざます」となにかひとつかふたつくらい？つっしーからみて缶バッチ向きなのどれだと思う？

**Comment by tussytussy** [comment]
全部いいな！！

そだな～、3つ選ぶとしたら「あざます」「がくぶる」「てへぺろ」かなー。
テレビも好きなんだけど、小さい缶バッジには収まりが悪いかもしんないな～と。

いや～、コレを１０コくらい鞄につけてる人いたら、なかなかクレイジーでいいな。

**Comment by tussytussy** [comment]
ここも完了したんでクローズします～
